
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Mon Jun 20 06:17:38 GMT+01:00 2022
//----------------------------------------------------

package fr.uha.hassenforder.javacup.sample.calculator;

/** CUP generated enum containing nonterminal constants. */
enum ENonterminal {
  /* nonterminals */
  list,
  instr,
  expr,
  eolnOpt,
  $START,
   ;
}

