
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Mon Jun 20 06:17:38 GMT+01:00 2022
//----------------------------------------------------

package fr.uha.hassenforder.javacup.sample.calculator;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   EQUAL,
   PLUS,
   MINUS,
   TIMES,
   DIVIDE,
   LPAREN,
   RPAREN,
   EOLN,
   NUMBER,
   ID,
   UPLUS,
   UMINUS,
   ;
}

