
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Mon Jun 20 06:17:37 GMT+01:00 2022
//----------------------------------------------------

package fr.uha.hassenforder.mdpi_parser;

/** CUP generated enum containing nonterminal constants. */
enum ENonterminal {
  /* nonterminals */
  paper,
  head,
  body,
  back,
  type,
  title,
  author,
  affiliations,
  affiliation,
  history,
  _abstract,
  keywords,
  line,
  sections,
  section,
  subSections,
  subSection,
  subSubSections,
  subSubSection,
  subSubSubSections,
  subSubSubSection,
  commonContents,
  commonContent,
  text,
  table,
  figure,
  equation,
  grid,
  gridContents,
  gridContent,
  figureHeader,
  figureFooter,
  emptyFigureCells,
  figureCells,
  figureCell,
  equationCells,
  equationCell,
  emptyTableCells,
  tableCaption,
  tableCells,
  tableCell,
  tableFooter,
  acks,
  ack,
  refs,
  ref,
  $START,
   ;
}

