
//----------------------------------------------------
// The following code was generated by jh-javacup-1.3 20220622
// Mon Jun 20 06:17:37 GMT+01:00 2022
//----------------------------------------------------

package fr.uha.hassenforder.mdpi_parser;

/** CUP generated enum containing terminal constants. */
public enum ETerminal {
  /* terminals */
   error,
   EOF,
   PARAGRAPH,
   TABLE_BEGIN,
   TABLE_END,
   ELECTION_FAILS,
   BLANK_LINE,
   MDPI11articletype,
   MDPI12title,
   MDPI13authornames,
   MDPI14history,
   MDPI16affiliation,
   MDPI17abstract,
   MDPI18keywords,
   MDPI19line,
   MDPI21heading1,
   MDPI22heading2,
   MDPI23heading3,
   MDPI29References,
   MDPI31text,
   MDPI39equation,
   MDPI3aequationnumber,
   MDPI41tablecaption,
   MDPI42tablebody,
   MDPI43tablefooter,
   MDPI51figurecaption,
   MDPI52figure,
   MDPI62Acknowledgments,
   MDPI71References,
   ;
}

